#TAG_COLOUR='#000000'
#NOTE_TEXT_COLOUR='#484445'
#DEFAULT_NOTE_COLOUR = '#FFFFFF' #white
#DEFAULT_PINNED_NOTE_BG_COLOUR = '#9D9784' #grey
#DEFAULT_SEARCH_RESULTS_BG_COLOUR = '#9D9784' #grey
#DEFAULT_TAGS_BG_COLOUR = '#9D9784' #grey

DATABASE_FILENAME = 'marcnotes_db'
APP_TITLE = " Scribe - ver 1.0 "
CONFIG_FILE = "./scribe.config"

#COLOURS
WIDGET_BACK_COLOUR = '#303234' # blackish
WIDGET_TEXT_COLOUR = '#e7edef' # off white (hint of blue)
NOTE_TEXT_COLOUR='#484445'
DEFAULT_NOTE_COLOUR = '#FFFFFF' #white